### ISSUE TITLE
Executable compenium template

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#110]
Following up [this discussion](https://fosstodon.org/@brodriguesco/109992981441539187), a usethis style compendium could be considered.

But, there are so many compendium formats available. We need to think about interoperability rather than XKCD 927. 

R specific

* https://github.com/ropensci/rrrpkg
* https://github.com/benmarwick/rrtools [paper](https://doi.org/10.1080/00031305.2017.1375986)
* https://github.com/FRBCesab/rcompendium/
* https://github.com/Pakillo/template
* https://github.com/jhollist/manuscriptPackage
* https://cran.r-project.org/web/packages/ProjectTemplate/

Sweave
* https://journal.r-project.org/archive/2011/RJ-2011-013/RJ-2011-013.pdf
* https://www.klinikum.uni-heidelberg.de/fileadmin/inst_med_biometrie/pdf/compHuang.pdf

Not R specific but can also be used to run R

* https://github.com/ccs-amsterdam/compendium

(white)papers

* https://docs.google.com/document/d/1LzZKS44y4OEJa4Azg5reGToNAZL0e0HSUwxamNY7E-Y/edit

**Comment by chainsawriot** [comment]
How about we just use the structure of [Turing](https://the-turing-way.netlify.app/reproducible-research/compendia.html) (rather than inventing something new):

```
compendium/
├── CITATION
├── code
│   ├── analyse_data.R
│   └── clean_data.R
├── data_clean
│   └── data_clean.csv
├── data_raw
│   ├── datapackage.json
│   └── data_raw.csv
├── Dockerfile
├── figures
│   └── flow_chart.jpeg
├── LICENSE
├── Makefile
├── paper.Rmd
└── README.md
```

It means that:

* We copy the `materials_dir` (assume that it contains `data_*`, `code` and `paper.Rmd`) as the `output_dir`.
* Place `Dockerfile`
* Create a directory called `rang` (or even `./inst/rang`) and put `cache` (if `cache` is `TRUE`) and `rang.R` there.
* In the `Dockerfile`, just `COPY * /*`
* Rewire the current `Dockerfile` to `RUN rang/rang.R`
* Rewire `cache` to `rang/cache` in `rang/rang.R`

**Comment by schochastics** [comment]
I was comparing the compendiums the other day and I also like the Turing way best. Lets go with that one.

**Comment by chainsawriot** [comment]
Maybe `inst/rang` is a better idea because we can also cover `rrtools`. We can just have a function called `rang::use_rang()` to insert our `rang` things into a format-independent existing compendium directory. We can also provide a function called `rang::use_turing()` to generate a basic structure.

Potential features / issues

- [ ] `Makefile` detection to insert `make` as a `sysreqs`
- [ ] How about `rrtools`' Quarto?
- [ ] Is [this real](https://github.com/benmarwick/rrtools/blob/master/inst/templates/render-in-docker.yaml)?

**Comment by schochastics** [comment]
I like the use_* approach. eventually one could also implement other compendiums like this. Can you help me understand the "is this real" comment. Is that a GHA to build a docker image?

**Comment by chainsawriot** [comment]
Quote from the [readme](https://github.com/benmarwick/rrtools)

> this also creates creates a minimal .yml configuration file to activate continuous integration using GitHub Actions. This will attempt to render your qmd document, in a Docker container specified by your Dockerfile, each time you push to GitHub. 

With this default Dockerfile

https://github.com/benmarwick/rrtools/blob/f71bddccf00d124512a8f20a4df08cd5e069f53e/inst/templates/Dockerfile#L1-L22

Too good to be true, e.g. no installation of Quarto CLI. But well, it says "attempt".

**Comment by schochastics** [comment]
oh ok that would be something :-O

**Comment by chainsawriot** [comment]
Tasks

- [x] `use_rang`
- [x] ~~`use_turing`~~ `create_turing`
- [x] A vignette
- [x] Integration of apptainer
- [x] Don't use `...` in `create_turing`

**Comment by chainsawriot** [comment]
https://github.com/gesistsa/rang/issues/159#issuecomment-1751719183
