### ISSUE TITLE
Support `bioc::`

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#58]
The issue is, we don't know enough about `bioc`.

**Comment by schochastics** [comment]
True. I have been looking at the code of [deepdep](https://github.com/DominikRafacz/deepdep) which supports `bioc`.

some lines of interest:
https://github.com/DominikRafacz/deepdep/blob/master/R/get_description.R#L102-L120

```r
``` r
tmp <- httr::GET("http://bioconductor.org/packages/release/bioc/VIEWS")
tmp <- httr::content(tmp, as = "text", encoding = "UTF-8")
pkgs <- deepdep:::prepeare_descs(tmp)
pkgs[[1]]
#> $Package
#> [1] "a4"
#> 
#> $Version
#> [1] "1.46.0"
#> 
#> $Depends
#> [1] "a4Base, a4Preproc, a4Classif, a4Core, a4Reporting"
#> 
#> $Suggests
#> [1] "MLP, nlcv, ALL, Cairo, Rgraphviz, GOstats"
#> 
#> $License
#> [1] "GPL-3"
#> 
#> $MD5sum
#> [1] "4fe2823df78513c79777d009196856fd"
#> 
#> $NeedsCompilation
#> [1] "no"
#> 
#> $Title
#> [1] "Automated Affymetrix Array Analysis Umbrella Package"
#> 
#> $Description
#> [1] "Umbrella package is available for the entire Automated Affymetrix Array Analysis suite of package."
#> 
#> $biocViews
#> [1] "Microarray"
#> 
#> $Author
#> [1] "Willem Talloen [aut], Tobias Verbeke [aut], Laure Cougnaud [cre]"
#> 
#> $Maintainer
#> [1] "Laure Cougnaud <laure.cougnaud@openanalytics.eu>"
#> 
#> $git_url
#> [1] "https://git.bioconductor.org/packages/a4"
#> 
#> $git_branch
#> [1] "RELEASE_3_16"
#> 
#> $git_last_commit
#> [1] "1b8f130"
#> 
#> $git_last_commit_date
#> [1] "2022-11-01"
#> 
#> $`Date/Publication`
#> [1] "2022-11-01"
#> 
#> $source.ver
#> [1] "src/contrib/a4_1.46.0.tar.gz"
#> 
#> $win.binary.ver
#> [1] "bin/windows/contrib/4.2/a4_1.46.0.zip"
#> 
#> $mac.binary.ver
#> [1] "bin/macosx/contrib/4.2/a4_1.46.0.tgz"
#> 
#> $`mac.binary.big-sur-arm64.ver`
#> [1] " bin/macosx/big-sur-arm64/contrib/4.2/a4_1.46.0.tgz"
#> 
#> $vignettes
#> [1] "vignettes/a4/inst/doc/a4vignette.pdf"
#> 
#> $vignetteTitles
#> [1] "a4vignette"
#> 
#> $hasREADME
#> [1] "FALSE"
#> 
#> $hasNEWS
#> [1] "TRUE"
#> 
#> $hasINSTALL
#> [1] "FALSE"
#> 
#> $hasLICENSE
#> [1] "FALSE"
#> 
#> $Rfiles
#> [1] "vignettes/a4/inst/doc/a4vignette.R"
#> 
#> $dependencyCount
#> [1] "83"
```
seems to have all the information. I continue to go down this rabbit hole

**Comment by schochastics** [comment]
In 
```
tmp <- httr::GET("http://bioconductor.org/packages/release/bioc/VIEWS")
```
release can be changed to other version numbers of bioc until 2.0 (doesnt work for 1.9-1.6)

**Comment by schochastics** [comment]
More references:

- good intro to Bioc: https://carpentries-incubator.github.io/bioc-project/03-installing-bioconductor/index.html
- Discussion on installing old versions: https://stackoverflow.com/questions/49487171/r-how-to-install-a-specified-version-of-a-bioconductor-package
- blog post on installing old packages: https://blog.tblein.eu/development/2016/installing-a-specific-version-of-bioconductor/
- Bioc docker: https://www.bioconductor.org/help/docker/
- releases: https://bioconductor.org/about/release-announcements/#release-announcements

"packages are not continuously updated as on CRAN but only with bioconductor releases in April/October" -> This probably makes thinks easier for us

**Comment by schochastics** [comment]
disentangling which dependencies are from CRAN and which from Bioconductor might become difficult

**Comment by schochastics** [comment]
Install packages:
Since 2018-06-15: 
```
install.packages("BiocManager")
BiocManager::install("BiocGenerics")
```
Before:
```
source("https://bioconductor.org/biocLite.R")
biocLite("BiocGenerics")
```

**Comment by chainsawriot** [comment]
The simplest solution is to peg `snapshot_date` with Bioconductor version

https://bioconductor.org/about/release-announcements/#release-versions

And get the VIEWS of that version

https://bioconductor.org/packages/2.5/bioc/VIEWS

There are finite number of bioc packages in that Bioconductor release. And dependency on bioc packages is only a thing for bioc packages.

bioc::x has a list of dependencies y.

For z in y {
if z is a bioc package in that Bioconductor Release {
dep_df$x_pkgref:= `bioc::x` dep_df$y_pkgref:=`bioc::z`}
dep_df$x_pkgref:= `bioc::x` dep_df$y_pkgref:=`cran::z`
}
}

**Comment by schochastics** [comment]
@chainsawriot have u stumbled upon some API that exposes the release dates as a json?
I created the cached version from [here](https://www.bioconductor.org/about/release-announcements/) but we would need something similar as in `.query_rver()` for upcoming releases

**Comment by chainsawriot** [comment]
@schochastics I haven't. But I think a machine readable version of [this](https://www.bioconductor.org/about/release-announcements/) could be of interest to [them](https://github.com/r-hub/rversions).

(rversions is also [scraping](https://github.com/r-hub/rversions/blob/055446cb6f7b8e3e4dd2038207bc115ee8d6ccd1/R/rversions.R).)

**Comment by chainsawriot** [comment]
Dockerization tests

- [x] `x <- resolve("bioc::BiocGenerics", snapshot_date = "2013-08-28")`
- [x] `x <- resolve("bioc::BiocGenerics", snapshot_date = "2023-02-20")`
- [x] `x <- resolve(c("bioc::BiocGenerics", "bioc::HDF5Array"), snapshot_date = "2013-08-28")` with Sysreqs
- [x] `x <- resolve(c("bioc::rsbml", "bioc::HDF5Array", "cran::xml2"), snapshot_date = "2023-02-20")` with Sysreqs
- [x] `x <- resolve(c("bioc::RBGL"), snapshot_date = "2012-12-20")`
- [x] `x <- resolve(c("bioc::BiocGenerics", "bioc::IRanges", "bioc::Biobase", "bioc::Biostrings", "bioc::GenomicRanges", "bioc::limma"), snapshot_date = "2012-12-20")`
- [x] `x <- resolve(c("bioc::Sushi", "bioc::genoset"), snapshot_date = "2014-04-16")` removed packages
- [x] `x <- resolve(c("bioc::Organism.dplyr"), snapshot_date = "2023-01-01")` dependency hell

**Comment by chainsawriot** [comment]
If #63 is implemented, the last two cases can be dockerized.

**Comment by chainsawriot** [comment]
Some of the most downloaded bioc packages

https://bioconductor.org/packages/stats/

Rhtslib, RBGL are some interesting candidates

**Comment by schochastics** [comment]
Here is one suggested from my sister:
https://www.bioconductor.org/packages/2.10/bioc/html/genoset.html
https://www.bioconductor.org/packages/3.12/bioc/html/genoset.html 

Seems to not be  on Bioc anymore.

**Comment by chainsawriot** [comment]
If #67 is implement, `x <- resolve(c("bioc::Sushi", "bioc::genoset"), snapshot_date = "2014-04-16")` can be dockerized.

**Comment by chainsawriot** [comment]
e472c06ad0b7cccafc87999fc4ba926fefed339a

```r
x <- resolve(c("bioc::Sushi", "bioc::genoset"), snapshot_date = "2014-04-16")
dockerize(x, output_dir = "~/dev/misc/bioc", no_rocker = TRUE, cache = TRUE)
```

**Comment by chainsawriot** [comment]
Tests self-tag @chainsawriot 

According to the Codecov report

- [x] sessionInfo with bioc
- [x] `resolve()` of pkgrefs with and without `bioc::`
- [x] .query_sysreqs_safe with `bioc::` (actually also with `github::`)
- [x] Refactor this a bit (reduce CYC)

https://github.com/chainsawriot/rang/blob/e1b7b971a0e9f5e532f0528653cb818ba31fa17f/R/resolve.R#L251-L268

**Comment by schochastics** [comment]
re CYC, I just added to that with #80 ... definitely needs a refactor

**Comment by chainsawriot** [comment]
@schochastics I think we can finally close this. The other issue is #92. But it is now not only a bioc issue.

Congrats!

**Comment by schochastics** [comment]
that was quite an adventure
