### ISSUE TITLE
Running `resolve()` for bioc packages from major release versions always fails

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#68]
```R
resolve("bioc::affy", snapshot_date = "2007-04-27") ## failed
## but this is fine
## resolve("bioc::affy", snapshot_date = "2007-10-09")
resolve("bioc::affy", snapshot_date = "2014-10-15") ## failed
## but this is fine
## resolve("bioc::affy", snapshot_date = "2015-04-18")
```

The reason for this is:

```R
.query_snapshot_dependencies_bioc("affy", "2014-10-15")
##Error in read.dcf(con) : 
##  cannot open the connection to 'http://bioconductor.org/packages/3/bioc/VIEWS'
##In addition: Warning message:
##In read.dcf(con) :
##  cannot open URL 'http://bioconductor.org/packages/3/bioc/VIEWS': HTTP status was '404 Not Found'
```

`cached_biocver` stores major versions as a single digit, while the url needs also the minor version.

http://bioconductor.org/packages/3.0/bioc/VIEWS

**Comment by chainsawriot** [comment]
#58

**Comment by chainsawriot** [comment]
`.biocver()` and `.cached_biocver` do not store `version` the same way (former as character, latter as numeric). Also, `.cached_biocver` doesn't have `attr(.cached_biocver, "newest_date")`.

**Comment by schochastics** [comment]
Yieks, i must have overwritten that by accident. I fix this

**Comment by chainsawriot** [comment]
@schochastics I fixed that already, but I am adding tests. And then I discover more issues. #69

**Comment by schochastics** [comment]
all right thanks
