### ISSUE TITLE
glue and cli available

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#72]
With `vctrs` introduced to fix #69, we can now use `glue` and `cli`. `vctrs` needs them anyway.

We can somehow

```R
.g <- glue::glue
handle <- "rtoot"
.g("cran::{handle}")
```

**Comment by schochastics** [comment]
any benefit of using this over `paste`?

**Comment by chainsawriot** [comment]
Performance-wise no. But the code would probably be less verbose, e.g. 

https://github.com/chainsawriot/rang/blob/eb00dbb0491cf50aa3e19a5a2069f1fef8d8003f/R/installation.R#L174

```r
cran_mirror <- "https://cran.r-project.org/"
x <- "mongolite"
version <- "2.7.1"
.g <- glue::glue

##paste
paste(cran_mirror, "src/contrib/Archive/", x, "/", x, "_", version, ".tar.gz", sep = "")
##g
.g("{cran_mirror}src/contrib/Archive/{x}/{x}_{version}.tar.gz")
```

**Comment by schochastics** [comment]
I let you make this call. Personally, I prefer `paste`, but I am fine with switching to `glue`

**Comment by chainsawriot** [comment]
Let's keep `paste` for now.
