### ISSUE TITLE
Empty `rang` behaviors

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#75]
Example

```r
graph <- readRDS("tests/testdata/rang_ok.RDS")
## similar to the case when all packages could't be resolved.
graph$ranglets <- list()
```

`print` looks okay.

`convert_edgelist` gives `NULL` (should it be an empty data.frame with `from` and `to`?)

`export_rang` gives an R file with an empty installation order. It runs but do nothing. (is it okay? Or at least some warnings?)

`dockerize` gives a directory. And building and launching it gives a vanilla R environment (it doesn't sound reasonable to me).

**Comment by schochastics** [comment]
see PR for `convert_edgelist`

I think `export_rang` should not produce a file at all given that there is nothing of use to be done with it?
Same for `dockerize` 

So maybe both return nothing finishing with a warning that there is nothing to export/dockerize?
