### ISSUE TITLE
Elimination of some dependencies?

### ISSUE THREAD

**Issue by chainsawriot** [chainsawriot/rang#94]
Now, we can analyze this package using this package.

```r
require(igraph)
x <- resolve("chainsawriot/rang", snapshot_date = "2023-02-25 10:00:00")
plot(graph_from_data_frame(convert_edgelist(x)), vertex.size = 0)
```

# gh

`httr2` is a deep dependency and it introduces a whole bunch of dependencies which we don't need. I was wondering if we can just use the good ol' `httr` or something similar to replace the two instances of `gh::gh`. The added benefit of using `httr` is that we can use `vcr` (as `Suggests`) to test the package (by replacing those `jsonlite::read_json` with `httr::content(httr::GET())`). But with `httr2` we can't (yet).

One issue is PAT (Personal Authentication Token). Probably only we (developers) need to care about it. But it's just about adding a header.

# anytime

This package needs `pkgsearch` and `pkgsearch` depends on `parsedate`. We can think about replacing `anytime` by `parsedate`. We don't need `Rcpp` and `BH`.

**Comment by schochastics** [comment]
Yes sounds like a good idea. If you are ok withit, Itake over this task

**Comment by chainsawriot** [comment]
@schochastics Great! Thank you!
